#!/bin/sh /etc/rc.common
# Omega_Garage Boot Script Created by James Harding
# https://github.com/JimJamUrCode for more...

START=99
STOP=1

start() {        
        echo start >> /tmp/output.txt
	git clone --progress https://github.com/JimJamUrCode/omega_garage.git /tmp/omega_garage 2> /root/gitoutput.log
	node /tmp/omega_garage/omega_garageServer.js 
}                 

stop() {          
        echo stop
        # commands to kill application 
}
